name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: npm ci
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Execute test 
        run: npm test
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: lint code
        run: npm run lint